
// Re-export types from validation schemas for consistency
export type {
  Comment,
  Court,
  TimeSlot,
  Participant,
  Reservation,
  User,
  Coach,
  CoachAvailability,
  Clinic,
  PrivateSession,
  DaySettings,
  ReservationSettings,
  CreateCourt,
  CreateTimeSlot,
  CreateReservation,
  CreateUser,
  CreateCoach,
  CreateClinic,
  CreatePrivateSession,
  CreateComment,
  UpdateReservation,
  UpdateUser,
  UpdateCoach,
  UpdateClinic,
  UpdatePrivateSession,
  UpdateTimeSlot,
} from './validation/schemas';
